title: neenjaw.com
email: tim@neenjaw.com
description: >-
  neenjaw.com
baseurl: ""
url: "https://neenjaw.com"
github_username: neenjaw
linkedin_username: timothyjaustin

date_format: "%b %-d, %Y"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - preact-components
  - README.md
  - Gemfile
  - Gemfile.lock
  - scripts
